# Site settings
title: 杜大叔的前端博客--返璞归真
email: uncledu@aliyun.com
description: > # this means to ignore newlines until "baseurl:"
    杜大叔的前端博客--返璞归真
baseurl: /lastjune.github.io/  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
twitter_username: uncledu_g
github_username:  lastjune

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  poetry:
    output: true
    permalink: /poetry/:path/


